### ISSUE TITLE
missing component

### ISSUE THREAD

**Issue by theoneakta** [mdhowle/ansible-ad-inventory#1]
libkrb5-dev needs to be install on os

**Comment by mdhowle** [comment]
libkrb5-dev is a dependency of gssapi if compiling from source or installing from pip. I have gssapi listed as an optional dependency. If you want to avoid compiling, you can use python-gssapi / python3-gssapi on Debian.

**Comment by theoneakta** [comment]
Ok thanks I will take notes and create a bootstrap for the config and test.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by theoneakta** [comment]
btw when i use adgroup with an ad group i have this error:

fatal: [V1SQLAX02D]: UNREACHABLE! => {"changed": false, "msg": "credssp: Server did not response with a CredSSP token after step Step 1. TLS Handshake - actual 'Negotiate, Kerberos, CredSSP'", "unreachable": true}

on every host of the security group

Any idea why?

I have winrm fonctionnal since i use ansible with a host file and all updates go through credssp winrm

I also checked the error and it refers to kerberos... do i need kerberos configured on my ubuntu for this to work?

Thanks in advance

________________________________

**Comment by theoneakta** [comment]
thanks
