### ISSUE TITLE
TLS disable

### ISSUE THREAD

**Issue by x09** [mdhowle/ansible-ad-inventory#10]
After upgrade from MS Windows 2008R2 to MS Windows 2012R2, all requests to AD - reset by peer. Microsoft turn off TLS  1,0 1,1 2,0.

I added new option to inventory config for enable/disable TLS
```
...
tls_enable: 'false'
...
```

diff plugins/inventory/ad/ad.py plugins/inventory/ad/ad.py.orig 
```
35,39d34
<         tls_enable:
<             description: Enabled TLS.
<             required: false
<             type: str
<             default: 'true'
173d167
<         tls_enable = self._get_option("tls_enable")
182,183c176
<             if tls_enable == "true":
<                 self._connection.start_tls() 
---
>             self._connection.start_tls()
```

**Comment by mdhowle** [comment]
As far as I'm aware, TLS 1.2 is supported and there is no TLS 2.0; do you mean SSL? In any case, I've added an option to toggle STARTTLS with `starttls: yes/no` with yes being default. I've also added an option to enable SSL explicitly with `ssl: yes` with it being no by default unless connecting via port 636, the standard LDAPS port.
