### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by valentusys** [mdhowle/ansible-ad-inventory#13]
1. Can I somehow declare a variable - to transfer it to the playbook?

2. Can I embed this plugin in my hosts.yml file?

3. Can I make different groups based on base or filter?

Thank you

**Comment by mdhowle** [comment]
1. You can set `var attribute: info` in ad.yml. Using Active Directory Users & Computers with Advanced Features enabled under the View menu, you can add YAML to info attribute to set attributes. See this [image](https://user-images.githubusercontent.com/1482847/149437784-4de72ef2-91ad-4b5d-8a31-0330085dd533.png).

2. Sorry, I'm not sure what you mean.

3. Unfortunately, you cannot at the moment. I'll look into adding this though. You would have to make different inventory files per group.
