### ISSUE TITLE
variables in the plugin

### ISSUE THREAD

**Issue by theoneakta** [mdhowle/ansible-ad-inventory#2]
Hi

I am trying to use ansible vault in the plugin. does not seem to work

ex:

in my vault file i have an entry password: 'password'
in the adgroup i have password: "{{password"}}

Can you enlight me please?

Thanks

**Comment by mdhowle** [comment]
I don't believe Ansible runs the plugin configuration file through Jinja2.

**Comment by mdhowle** [comment]
I initially thought it may be possible to obtain the variables and have the plugin process any template variables. However, after some digging, it appears inventory plugins do not have access to extra-vars in Ansible version <=2.10

It looks like it may be possible in 2.11. See https://github.com/ansible/ansible/pull/70970

**Comment by theoneakta** [comment]
Thank you

Looking forward to it :)

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
