### ISSUE TITLE
Roles

### ISSUE THREAD

**Issue by theoneakta** [mdhowle/ansible-ad-inventory#3]
Can we call the adgroup host yml files in a role? does not seem like i find the way. is it possible?

**Comment by mdhowle** [comment]
I'm not sure what you mean. This is an inventory plugin so it only populates the inventory. What are you attempting to do?

**Comment by theoneakta** [comment]
You can close this request

I figured it out

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
