### ISSUE TITLE
how do I configure the plugin in ansible to use it in the playbook?

### ISSUE THREAD

**Issue by shabbir1679** [mdhowle/ansible-ad-inventory#4]

**Comment by mdhowle** [comment]
This is in the README. Install the plugin in your Ansible environment (see [Adding a plugin locally](https://docs.ansible.com/ansible/latest/dev_guide/developing_locally.html#adding-a-plugin-locally)).

After it's installed create `ad.yml` file in your project directory with the following contents, and run it `ansible-playbook -i ad.yml someplaybook.yml`. If it doesn't work, run `ansible-playbook` again including `-vvv` to see where Ansible might be failing.

```
plugin: ad
server: dc.example.com
port: 636
base: DC=example,DC=com
username: EXAMPLE\ExampleUser  # or distinguishedname
password: hunter2
filter: "(operatingSystem='Debian GNU/Linux')"
ansible group: Debian
var attribute: info
```
