### ISSUE TITLE
How set key for ssh access

### ISSUE THREAD

**Issue by x09** [mdhowle/ansible-ad-inventory#5]
my ad.yml
```

plugin: ad
server:my-ad-server
port: 3268
base: "OU=computers,DC=adm,DC=local"
username: "cn=viewer,ou=LDAP,ou=Special,dc=adm,dc=local"
password: superpass
ansible group: altlinux-p9
ansible_ssh_private_key_file: /root/.ssh/manager
user: root
```

but i get error
fatal: [altp9-ansible-node4]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: root@altp9-ansible-node4: Permission denied (publickey,password).", "unreachable": true}

how use my private key in /root/.ssh/manager ?

**Comment by mdhowle** [comment]
That's not a parameter for the plugin and doesn't belong in `ad.yml`. To set your private key, add the parameter `--private-key /root/.ssh/manager` when calling ansible. Alternatively, set `DEFAULT_PRIVATE_KEY_FILE` in `~/.ansible.cfg`, or set the environment variable `ANSIBLE_PRIVATE_KEY_FILE=/root/.ssh/manager`.
